apiVersion: v1
kind: Namespace
metadata:
  name: crane-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crane-scheduler-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - list
  - watch
  - get
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crane-scheduler-controller
  namespace: crane-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crane-scheduler-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crane-scheduler-controller
subjects:
- kind: ServiceAccount
  name: crane-scheduler-controller
  namespace: crane-system