apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
clientConnection:
  kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
profiles:
  - schedulerName: default-scheduler
    plugins:
      filter:
        enabled:
          - name: ApplicationResourceAware
    pluginConfig:
      - name: ApplicationResourceAware
        args:
          policyConfigPath: /etc/kubernetes/policy.yaml